; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{07295CC3-0FC8-4076-AA15-DAEE0156D372}
AppName=CiphersApp
AppVersion=0.8
;AppVerName=CiphersApp 0.8
DefaultDirName=C:\CiphersApp
UninstallDisplayIcon={app}\Ciphers.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DefaultGroupName=CiphersApp
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\kvrun\OneDrive\Рабочий стол
OutputBaseFilename=mysetup
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Release(kinda)\Ciphers.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Release(kinda)\Config.env"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Release(kinda)\Ciphers\*"; DestDir: "{app}\Ciphers"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Release(kinda)\static\*"; DestDir: "{app}\static"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Release(kinda)\templates\*"; DestDir: "{app}\templates"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Release(kinda)\vc_redist.x64.exe"; DestDir: "{app}"; Flags: deleteafterinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename: "{app}\vc_redist.x64.exe"; Parameters: "/install /quiet /norestart"; StatusMsg: "Устанавливаем Microsoft Visual C++ Redistributable (x64)"

[Registry]
Root: HKA; Subkey: "Software\Classes\.myp\OpenWithProgids"; ValueType: string; ValueName: "CiphersAppFile.myp"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\CiphersAppFile.myp"; ValueType: string; ValueName: ""; ValueData: "Ciphers App File"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\CiphersAppFile.myp\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\Ciphers.exe,0"
Root: HKA; Subkey: "Software\Classes\CiphersAppFile.myp\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\Ciphers.exe"" ""%1"""

[Icons]
Name: "{group}\Ciphers App"; Filename: "{app}\Ciphers.exe"
Name: "{autodesktop}\Ciphers App"; Filename: "{app}\Ciphers.exe"; Tasks: desktopicon

[Code]
procedure RedactEnvFile(FilePath: string);
var
  Lines: TStringList;
  i: Integer;
  key: String;
  AppDir: String;
begin
  AppDir := ExpandConstant('{app}');
  Lines := TStringList.Create;
  try
    // Load the .env file
    Lines.LoadFromFile(FilePath);

    // Loop through each line and redact sensitive values
    for i := 0 to Lines.Count - 1 do
    begin
      if Pos('=', Lines[i]) > 0 then
      begin
        Key := Trim(Copy(Lines[i], 1, Pos('=', Lines[i]) - 1));
        if (Key = 'BASE_DIR_PATH') then
        begin
          Lines[i] := Key + '=' + AppDir;
          Break;
        end;
      end;
    end;

    // Save the modified .env file
    Lines.SaveToFile(FilePath);
  finally
    Lines.Free;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  // Redact the .env file after it has been installed
  if CurStep = ssPostInstall then
  begin
    RedactEnvFile(ExpandConstant('{app}\Config.env'));
  end;
end;
[Run]
Filename: "{app}\Ciphers.exe"; Description: "{cm:LaunchProgram,CiphersApp}"; Flags: nowait postinstall skipifsilent

